*****  This Stata do-file aggregates some of the variables of the V-Dem and RoW data
*****  Author: Bastian Herre
*****  May 25, 2023

version 14
clear all
set more off
set varabbrev off


** Set your own working directories here to run the file:
cd "/Users/bastianherre/Dropbox/Data/"
global project "/Users/bastianherre/Dropbox/Data/"


** Aggregate by year to create world aggregates for sums and averages of regime variables:

* Import data:
use "democracy/datasets/refined/vdem_row_refined.dta", clear

* Only aggregate countries without imputed values:
replace regime_row_owid = . if regime_imputed_vdem_owid == 1
replace regime_amb_row_owid = . if regime_imputed_vdem_owid == 1
replace electdem_age_group_row_owid = . if regime_imputed_vdem_owid == 1
replace libdem_age_group_row_owid = . if regime_imputed_vdem_owid == 1
replace wom_parl_gr_vdem_owid = . if regime_imputed_vdem_owid == 1
replace wom_hog_vdem_owid = . if regime_imputed_vdem_owid == 1
replace wom_hos_vdem_owid = . if regime_imputed_vdem_owid == 1
replace wom_hoe_vdem_owid = . if regime_imputed_vdem_owid == 1

* Create indicator variables for specific regime categories:
tabulate regime_row_owid, generate(regime_row_owid)
tabulate regime_amb_row_owid, generate(regime_amb_row_owid)
tabulate electdem_age_group_row_owid, generate(electdem_age_group_row_owid)
tabulate libdem_age_group_row_owid, generate(libdem_age_group_row_owid)
tabulate wom_parl_gr_vdem_owid, generate(wom_parl_gr_vdem_owid)
tabulate wom_hog_vdem_owid, generate(wom_hog_vdem_owid)
tabulate wom_hos_vdem_owid, generate(wom_hos_vdem_owid)
tabulate wom_hoe_vdem_owid, generate(wom_hoe_vdem_owid)

* Collapse dataset by year:
collapse (sum) regime_row_owid* regime_amb_row_owid* electdem_age_group_row_owid* libdem_age_group_row_owid* wom_parl_gr_vdem_owid* wom_hog_vdem_owid* wom_hos_vdem_owid* wom_hoe_vdem_owid* ///
	(mean) electdem_vdem_owid electdem_vdem_low_owid electdem_vdem_high_owid libdem_vdem_owid libdem_vdem_low_owid libdem_vdem_high_owid participdem_vdem_owid participdem_vdem_low_owid participdem_vdem_high_owid delibdem_vdem_owid delibdem_vdem_low_owid delibdem_vdem_high_owid egaldem_vdem_owid egaldem_vdem_low_owid egaldem_vdem_high_owid ///
	civ_libs_vdem_owid civ_libs_vdem_high_owid civ_libs_vdem_low_owid phys_integr_libs_vdem_owid phys_integr_libs_vdem_high_owid phys_integr_libs_vdem_low_owid pol_libs_vdem_owid pol_libs_vdem_high_owid pol_libs_vdem_low_owid priv_libs_vdem_owid priv_libs_vdem_high_owid priv_libs_vdem_low_owid ///
	wom_emp_vdem_owid wom_emp_vdem_high_owid wom_emp_vdem_low_owid wom_civ_libs_vdem_owid wom_civ_libs_vdem_high_owid wom_civ_libs_vdem_low_owid wom_civ_soc_vdem_owid wom_civ_soc_vdem_high_owid wom_civ_soc_vdem_low_owid wom_pol_par_vdem_owid wom_pol_par_vdem_high_owid wom_pol_par_vdem_low_owid wom_parl_vdem_owid ///
	socgr_civ_libs_vdem_owid socgr_civ_libs_vdem_high_owid socgr_civ_libs_vdem_low_owid socgr_pow_vdem_owid socgr_pow_vdem_high_owid socgr_pow_vdem_low_owid ///
	terr_contr_vdem_owid terr_contr_vdem_high_owid terr_contr_vdem_low_owid rule_of_law_vdem_owid rule_of_law_vdem_high_owid rule_of_law_vdem_low_owid public_admin_vdem_owid public_admin_vdem_high_owid public_admin_vdem_low_owid int_auton_vdem_owid int_auton_vdem_high_owid int_auton_vdem_low_owid dom_auton_vdem_owid dom_auton_vdem_high_owid dom_auton_vdem_low_owid ///
	corruption_vdem_owid corruption_vdem_high_owid corruption_vdem_low_owid corr_publsec_vdem_owid corr_publsec_vdem_high_owid corr_publsec_vdem_low_owid corr_exec_vdem_owid corr_exec_vdem_high_owid corr_exec_vdem_low_owid corr_leg_vdem_owid corr_leg_vdem_high_owid corr_leg_vdem_low_owid corr_jud_vdem_owid corr_jud_vdem_high_owid corr_jud_vdem_low_owid ///
	personalism_vdem_owid personalism_vdem_high_owid personalism_vdem_low_owid civ_soc_str_vdem_owid civ_soc_str_vdem_high_owid civ_soc_str_vdem_low_owid, by(year)
drop regime_row_owid regime_amb_row_owid electdem_age_group_row_owid libdem_age_group_row_owid wom_parl_gr_vdem_owid wom_hog_vdem_owid wom_hos_vdem_owid wom_hoe_vdem_owid

* Create entity identifier:
generate country_name = "World"

* Rename variables:
rename regime_row_owid1 number_closedaut_row_owid
rename regime_row_owid2 number_electaut_row_owid
rename regime_row_owid3 number_electdem_row_owid
rename regime_row_owid4 number_libdem_row_owid

rename regime_amb_row_owid1 number_closedaut_amb_row_owid
rename regime_amb_row_owid2 number_closedaut_h_amb_row_owid
rename regime_amb_row_owid3 number_electaut_l_amb_row_owid
rename regime_amb_row_owid4 number_electaut_amb_row_owid
rename regime_amb_row_owid5 number_electaut_h_amb_row_owid
rename regime_amb_row_owid6 number_electdem_l_amb_row_owid
rename regime_amb_row_owid7 number_electdem_amb_row_owid
rename regime_amb_row_owid8 number_electdem_h_amb_row_owid
rename regime_amb_row_owid9 number_libdem_l_amb_row_owid
rename regime_amb_row_owid10 number_libdem_amb_row_owid

drop electdem_age_group_row_owid1 electdem_age_group_row_owid2
rename electdem_age_group_row_owid3 number_electdem_18_row_owid
rename electdem_age_group_row_owid4 number_electdem_30_row_owid
rename electdem_age_group_row_owid5 number_electdem_60_row_owid
rename electdem_age_group_row_owid6 number_electdem_90_row_owid
rename electdem_age_group_row_owid7 number_electdem_91plus_row_owid

drop libdem_age_group_row_owid1 libdem_age_group_row_owid2 libdem_age_group_row_owid3
rename libdem_age_group_row_owid4 number_libdem_18_row_owid
rename libdem_age_group_row_owid5 number_libdem_30_row_owid
rename libdem_age_group_row_owid6 number_libdem_60_row_owid
rename libdem_age_group_row_owid7 number_libdem_90_row_owid
rename libdem_age_group_row_owid8 number_libdem_91plus_row_owid

rename wom_parl_gr_vdem_owid1 number_nowomen_vdem_owid
rename wom_parl_gr_vdem_owid2 number_less10women_vdem_owid
rename wom_parl_gr_vdem_owid3 number_less20women_vdem_owid
rename wom_parl_gr_vdem_owid4 number_less30women_vdem_owid
rename wom_parl_gr_vdem_owid5 number_less40women_vdem_owid
rename wom_parl_gr_vdem_owid6 number_less50women_vdem_owid
rename wom_parl_gr_vdem_owid7 number_more50women_vdem_owid

rename wom_hog_vdem_owid1 number_hog_men_vdem_owid
rename wom_hog_vdem_owid2 number_hog_women_vdem_owid

rename wom_hos_vdem_owid1 number_hos_men_vdem_owid
rename wom_hos_vdem_owid2 number_hos_women_vdem_owid

rename wom_hoe_vdem_owid1 number_hoe_men_vdem_owid
rename wom_hoe_vdem_owid2 number_hoe_women_vdem_owid

* Temporarily save data:
save "democracy/datasets/final/vdem_row_aggregated.dta", replace


** Aggregate by year to create world aggregates for population-weighted sums and averages of regime variables:

* Import data:
use "democracy/datasets/refined/vdem_row_refined.dta", clear

* Add population data:
merge 1:1 country_name year using "Our World in Data/owid_population_cleaned.dta"
tab country_name if _merge == 1 & year >= 1800 // Unmerged observations in master datasets either before 1800, historical countries (Two Sicilies, East Germany) or current countries without population data (Kosovo, Palestine/Gaza, Palestine/West Bank, Somaliland).
drop _merge

* Recode regime classification such that it includes a category for when population data is available, but regime data is missing:
replace regime_row_owid = 4 if regime_row_owid == . & population_owid != .
label values regime_row_owid regime_row_owid
label define regime_row_owid 4 "no regime data", add

replace regime_amb_row_owid = 10 if regime_amb_row_owid == . & population_owid != .
label values regime_amb_row_owid regime_row_owid
label define regime_amb_row_owid 10 "no regime data", add
drop if population_owid == .

replace wom_hog_vdem_owid = 3 if wom_hog_vdem_owid == . & population_owid != .
label values wom_hog_vdem_owid wom_hog_vdem_owid
label define wom_hog_vdem_owid 3 "no gender data", add

replace wom_hos_vdem_owid = 3 if wom_hos_vdem_owid == . & population_owid != .
label values wom_hos_vdem_owid wom_hos_vdem_owid
label define wom_hos_vdem_owid 3 "no gender data", add

replace wom_hoe_vdem_owid = 3 if wom_hoe_vdem_owid == . & population_owid != .
label values wom_hoe_vdem_owid wom_hoe_vdem_owid
label define wom_hoe_vdem_owid 3 "no gender data", add

* Here, I also aggregate countries with imputed values — because people matter here, not countries.

* Create indicator variables for specific regime categories:
tabulate regime_row_owid, generate(regime_row_owid)
tabulate regime_amb_row_owid, generate(regime_amb_row_owid)
tabulate electdem_age_group_row_owid, generate(electdem_age_group_row_owid)
tabulate libdem_age_group_row_owid, generate(libdem_age_group_row_owid)
tabulate wom_hog_vdem_owid, generate(wom_hog_vdem_owid)
tabulate wom_hos_vdem_owid, generate(wom_hos_vdem_owid)
tabulate wom_hoe_vdem_owid, generate(wom_hoe_vdem_owid)

* Collapse dataset by year:
collapse (sum) regime_row_owid* regime_amb_row_owid* electdem_age_group_row_owid* libdem_age_group_row_owid* wom_hog_vdem_owid* wom_hos_vdem_owid* wom_hoe_vdem_owid* ///
	(mean) electdem_vdem_owid electdem_vdem_low_owid electdem_vdem_high_owid libdem_vdem_owid libdem_vdem_low_owid libdem_vdem_high_owid participdem_vdem_owid participdem_vdem_low_owid participdem_vdem_high_owid delibdem_vdem_owid delibdem_vdem_low_owid delibdem_vdem_high_owid egaldem_vdem_owid egaldem_vdem_low_owid egaldem_vdem_high_owid ///
	civ_libs_vdem_owid civ_libs_vdem_high_owid civ_libs_vdem_low_owid phys_integr_libs_vdem_owid phys_integr_libs_vdem_high_owid phys_integr_libs_vdem_low_owid pol_libs_vdem_owid pol_libs_vdem_high_owid pol_libs_vdem_low_owid priv_libs_vdem_owid priv_libs_vdem_high_owid priv_libs_vdem_low_owid ///
	wom_emp_vdem_owid wom_emp_vdem_high_owid wom_emp_vdem_low_owid wom_civ_libs_vdem_owid wom_civ_libs_vdem_high_owid wom_civ_libs_vdem_low_owid wom_civ_soc_vdem_owid wom_civ_soc_vdem_high_owid wom_civ_soc_vdem_low_owid wom_pol_par_vdem_owid wom_pol_par_vdem_high_owid wom_pol_par_vdem_low_owid wom_parl_vdem_owid ///
	socgr_civ_libs_vdem_owid socgr_civ_libs_vdem_high_owid socgr_civ_libs_vdem_low_owid socgr_pow_vdem_owid socgr_pow_vdem_high_owid socgr_pow_vdem_low_owid ///
	terr_contr_vdem_owid terr_contr_vdem_high_owid terr_contr_vdem_low_owid rule_of_law_vdem_owid rule_of_law_vdem_high_owid rule_of_law_vdem_low_owid public_admin_vdem_owid public_admin_vdem_high_owid public_admin_vdem_low_owid int_auton_vdem_owid int_auton_vdem_high_owid int_auton_vdem_low_owid dom_auton_vdem_owid dom_auton_vdem_high_owid dom_auton_vdem_low_owid ///
	corruption_vdem_owid corruption_vdem_high_owid corruption_vdem_low_owid corr_publsec_vdem_owid corr_publsec_vdem_high_owid corr_publsec_vdem_low_owid corr_exec_vdem_owid corr_exec_vdem_high_owid corr_exec_vdem_low_owid corr_leg_vdem_owid corr_leg_vdem_high_owid corr_leg_vdem_low_owid corr_jud_vdem_owid corr_jud_vdem_high_owid corr_jud_vdem_low_owid ///
	personalism_vdem_owid personalism_vdem_high_owid personalism_vdem_low_owid civ_soc_str_vdem_owid civ_soc_str_vdem_high_owid civ_soc_str_vdem_low_owid [fweight = population_owid], by(year)
drop regime_row_owid regime_amb_row_owid regime_amb_row_owid11 electdem_age_group_row_owid libdem_age_group_row_owid wom_hog_vdem_owid wom_hos_vdem_owid wom_hoe_vdem_owid

* Create entity identifier:
generate country_name = "World"

* Rename variables:
rename regime_row_owid1 pop_closedaut_row_owid
rename regime_row_owid2 pop_electaut_row_owid
rename regime_row_owid3 pop_electdem_row_owid
rename regime_row_owid4 pop_libdem_row_owid
rename regime_row_owid5 pop_missreg_row_owid

rename regime_amb_row_owid1 pop_closedaut_amb_row_owid
rename regime_amb_row_owid2 pop_closedaut_h_amb_row_owid
rename regime_amb_row_owid3 pop_electaut_l_amb_row_owid
rename regime_amb_row_owid4 pop_electaut_amb_row_owid
rename regime_amb_row_owid5 pop_electaut_h_amb_row_owid
rename regime_amb_row_owid6 pop_electdem_l_amb_row_owid
rename regime_amb_row_owid7 pop_electdem_amb_row_owid
rename regime_amb_row_owid8 pop_electdem_h_amb_row_owid
rename regime_amb_row_owid9 pop_libdem_l_amb_row_owid
rename regime_amb_row_owid10 pop_libdem_amb_row_owid

drop electdem_age_group_row_owid1 electdem_age_group_row_owid2
rename electdem_age_group_row_owid3 pop_electdem_18_row_owid
rename electdem_age_group_row_owid4 pop_electdem_30_row_owid
rename electdem_age_group_row_owid5 pop_electdem_60_row_owid
rename electdem_age_group_row_owid6 pop_electdem_90_row_owid
rename electdem_age_group_row_owid7 pop_electdem_91plus_row_owid

drop libdem_age_group_row_owid1 libdem_age_group_row_owid2 libdem_age_group_row_owid3
rename libdem_age_group_row_owid4 pop_libdem_18_row_owid
rename libdem_age_group_row_owid5 pop_libdem_30_row_owid
rename libdem_age_group_row_owid6 pop_libdem_60_row_owid
rename libdem_age_group_row_owid7 pop_libdem_90_row_owid
rename libdem_age_group_row_owid8 pop_libdem_91plus_row_owid

rename wom_hog_vdem_owid1 pop_hog_men_vdem_owid
rename wom_hog_vdem_owid2 pop_hog_women_vdem_owid
rename wom_hog_vdem_owid3 pop_hog_missgen_vdem_owid

rename wom_hos_vdem_owid1 pop_hos_men_vdem_owid
rename wom_hos_vdem_owid2 pop_hos_women_vdem_owid
rename wom_hos_vdem_owid3 pop_hos_missgen_vdem_owid

rename wom_hoe_vdem_owid1 pop_hoe_men_vdem_owid
rename wom_hoe_vdem_owid2 pop_hoe_women_vdem_owid
rename wom_hoe_vdem_owid3 pop_hoe_missgen_vdem_owid

rename electdem_vdem_owid popw_electdem_vdem_owid
rename electdem_vdem_low_owid popw_electdem_l_vdem_owid
rename electdem_vdem_high_owid popw_electdem_h_vdem_owid

rename libdem_vdem_owid popw_libdem_vdem_owid
rename libdem_vdem_low_owid popw_libdem_l_vdem_owid
rename libdem_vdem_high_owid popw_libdem_h_vdem_owid

rename participdem_vdem_owid popw_participdem_vdem_owid
rename participdem_vdem_low_owid popw_participdem_l_vdem_owid
rename participdem_vdem_high_owid popw_participdem_h_vdem_owid

rename delibdem_vdem_owid popw_delibdem_vdem_owid
rename delibdem_vdem_low_owid popw_delibdem_l_vdem_owid
rename delibdem_vdem_high_owid popw_delibdem_h_vdem_owid

rename egaldem_vdem_owid popw_egaldem_vdem_owid
rename egaldem_vdem_low_owid popw_egaldem_l_vdem_owid
rename egaldem_vdem_high_owid popw_egaldem_h_vdem_owid

rename civ_libs_vdem_owid popw_civ_libs_vdem_owid
rename civ_libs_vdem_high_owid popw_civ_libs_vdem_high_owid
rename civ_libs_vdem_low_owid popw_civ_libs_vdem_low_owid

rename phys_integr_libs_vdem_owid popw_physinteg_libs_vdem_owid
rename phys_integr_libs_vdem_high_owid popw_physinteg_libs_vdem_h_owid
rename phys_integr_libs_vdem_low_owid popw_physinteg_libs_vdem_l_owid

rename pol_libs_vdem_owid popw_pol_libs_vdem_owid
rename pol_libs_vdem_high_owid popw_pol_libs_vdem_high_owid
rename pol_libs_vdem_low_owid popw_pol_libs_vdem_low_owid

rename priv_libs_vdem_owid popw_priv_libs_vdem_owid
rename priv_libs_vdem_high_owid popw_priv_libs_vdem_high_owid
rename priv_libs_vdem_low_owid popw_priv_libs_vdem_low_owid

rename wom_emp_vdem_owid popw_wom_emp_vdem_owid
rename wom_emp_vdem_high_owid popw_wom_emp_vdem_high_owid
rename wom_emp_vdem_low_owid popw_wom_emp_vdem_low_owid

rename wom_civ_libs_vdem_owid popw_wom_civ_libs_vdem_owid
rename wom_civ_libs_vdem_high_owid popw_wom_civ_libs_vdem_high_owid
rename wom_civ_libs_vdem_low_owid popw_wom_civ_libs_vdem_low_owid

rename wom_civ_soc_vdem_owid popw_wom_civ_soc_vdem_owid
rename wom_civ_soc_vdem_high_owid popw_wom_civ_soc_vdem_high_owid
rename wom_civ_soc_vdem_low_owid popw_wom_civ_soc_vdem_low_owid

rename wom_pol_par_vdem_owid popw_wom_pol_par_vdem_owid
rename wom_pol_par_vdem_high_owid popw_wom_pol_par_vdem_high_owid
rename wom_pol_par_vdem_low_owid popw_wom_pol_par_vdem_low_owid

rename wom_parl_vdem_owid popw_wom_parl_vdem_owid

rename socgr_civ_libs_vdem_owid popw_socgr_civ_libs_vdem_owid
rename socgr_civ_libs_vdem_high_owid popw_socgr_civ_libs_vdem_h_owid
rename socgr_civ_libs_vdem_low_owid popw_socgr_civ_libs_vdem_l_owid

rename socgr_pow_vdem_owid popw_socgr_pow_vdem_owid
rename socgr_pow_vdem_high_owid popw_socgr_pow_vdem_high_owid
rename socgr_pow_vdem_low_owid popw_socgr_pow_vdem_low_owid

rename terr_contr_vdem_owid popw_terr_contr_vdem_owid
rename terr_contr_vdem_high_owid popw_terr_contr_vdem_high_owid
rename terr_contr_vdem_low_owid popw_terr_contr_vdem_low_owid

rename rule_of_law_vdem_owid popw_rule_of_law_vdem_owid
rename rule_of_law_vdem_high_owid popw_rule_of_law_vdem_high_owid
rename rule_of_law_vdem_low_owid popw_rule_of_law_vdem_low_owid

rename public_admin_vdem_owid popw_public_admin_vdem_owid
rename public_admin_vdem_high_owid popw_public_admin_vdem_high_owid
rename public_admin_vdem_low_owid popw_public_admin_vdem_low_owid

rename int_auton_vdem_owid popw_int_auton_vdem_owid
rename int_auton_vdem_high_owid popw_int_auton_vdem_high_owid
rename int_auton_vdem_low_owid popw_int_auton_vdem_low_owid

rename dom_auton_vdem_owid popw_dom_auton_vdem_owid
rename dom_auton_vdem_high_owid popw_dom_auton_vdem_high_owid
rename dom_auton_vdem_low_owid popw_dom_auton_vdem_low_owid

rename corruption_vdem_owid popw_corruption_vdem_owid
rename corruption_vdem_high_owid popw_corruption_vdem_high_owid
rename corruption_vdem_low_owid popw_corruption_vdem_low_owid

rename corr_publsec_vdem_owid popw_corr_publsec_vdem_owid
rename corr_publsec_vdem_high_owid popw_corr_publsec_vdem_high_owid
rename corr_publsec_vdem_low_owid popw_corr_publsec_vdem_low_owid

rename corr_exec_vdem_owid popw_corr_exec_vdem_owid
rename corr_exec_vdem_high_owid popw_corr_exec_vdem_high_owid
rename corr_exec_vdem_low_owid popw_corr_exec_vdem_low_owid

rename corr_leg_vdem_owid popw_corr_leg_vdem_owid
rename corr_leg_vdem_high_owid popw_corr_leg_vdem_high_owid
rename corr_leg_vdem_low_owid popw_corr_leg_vdem_low_owid

rename corr_jud_vdem_owid popw_corr_jud_vdem_owid
rename corr_jud_vdem_high_owid popw_corr_jud_vdem_high_owid
rename corr_jud_vdem_low_owid popw_corr_jud_vdem_low_owid

rename personalism_vdem_owid popw_personalism_vdem_owid
rename personalism_vdem_high_owid popw_personalism_vdem_high_owid
rename personalism_vdem_low_owid popw_personalism_vdem_low_owid

rename civ_soc_str_vdem_owid popw_civ_soc_str_vdem_owid
rename civ_soc_str_vdem_high_owid popw_civ_soc_str_vdem_high_owid
rename civ_soc_str_vdem_low_owid popw_civ_soc_str_vdem_low_owid

* Temporarily save data:
save "democracy/datasets/final/vdem_row_aggregated_popweighted.dta", replace


** Aggregate by year and region to create regional aggregates for sums and averages of regime variables:

* Prepare regional identifiers:
import delimited "Our World in Data/countries_regions_pairs.csv", clear varnames(1)
rename country country_name

* Keep regional identifiers of interest:
tab region
drop if region == "Antarctica"
duplicates tag country_name, generate(duplicate)
list if duplicate == 1
drop if region == "European Union (27)"
duplicates drop // Northern Cyprus still listed twice.
drop duplicate

save "Our World in Data/countries_regions_pairs.dta", replace

* Import data:
use "democracy/datasets/refined/vdem_row_refined.dta", clear

* Add regional identifiers:
merge m:1 country_name using "Our World in Data/countries_regions_pairs.dta"
tab country_name if _merge == 1
replace region = "Europe" if country_name == "Brunswick" | country_name == "Hamburg" | country_name == "Nassau" | country_name == "Oldenburg" | country_name == "Papal States" | country_name == "Piedmont-Sardinia" | country_name == "Saxe-Weimar-Eisenach"
replace region = "Asia" if country_name == "Palestine/Gaza" | country_name == "Palestine/West Bank"
drop if _merge == 2
drop _merge

* Only aggregate countries without imputed values:
replace regime_row_owid = . if regime_imputed_vdem_owid == 1
replace regime_amb_row_owid = . if regime_imputed_vdem_owid == 1
replace electdem_age_group_row_owid = . if regime_imputed_vdem_owid == 1
replace libdem_age_group_row_owid = . if regime_imputed_vdem_owid == 1
replace wom_parl_gr_vdem_owid = . if regime_imputed_vdem_owid == 1
replace wom_hog_vdem_owid = . if regime_imputed_vdem_owid == 1
replace wom_hos_vdem_owid = . if regime_imputed_vdem_owid == 1
replace wom_hoe_vdem_owid = . if regime_imputed_vdem_owid == 1

* Create indicator variables for specific regime categories:
tabulate regime_row_owid, generate(regime_row_owid)
tabulate regime_amb_row_owid, generate(regime_amb_row_owid)
tabulate electdem_age_group_row_owid, generate(electdem_age_group_row_owid)
tabulate libdem_age_group_row_owid, generate(libdem_age_group_row_owid)
tabulate wom_parl_gr_vdem_owid, generate(wom_parl_gr_vdem_owid)
tabulate wom_hog_vdem_owid, generate(wom_hog_vdem_owid)
tabulate wom_hos_vdem_owid, generate(wom_hos_vdem_owid)
tabulate wom_hoe_vdem_owid, generate(wom_hoe_vdem_owid)

* Collapse dataset by year:
collapse (sum) regime_row_owid* regime_amb_row_owid* electdem_age_group_row_owid* libdem_age_group_row_owid* wom_parl_gr_vdem_owid* wom_hog_vdem_owid* wom_hos_vdem_owid* wom_hoe_vdem_owid* ///
	(mean) electdem_vdem_owid electdem_vdem_low_owid electdem_vdem_high_owid libdem_vdem_owid libdem_vdem_low_owid libdem_vdem_high_owid participdem_vdem_owid participdem_vdem_low_owid participdem_vdem_high_owid delibdem_vdem_owid delibdem_vdem_low_owid delibdem_vdem_high_owid egaldem_vdem_owid egaldem_vdem_low_owid egaldem_vdem_high_owid ///
	civ_libs_vdem_owid civ_libs_vdem_high_owid civ_libs_vdem_low_owid phys_integr_libs_vdem_owid phys_integr_libs_vdem_high_owid phys_integr_libs_vdem_low_owid pol_libs_vdem_owid pol_libs_vdem_high_owid pol_libs_vdem_low_owid priv_libs_vdem_owid priv_libs_vdem_high_owid priv_libs_vdem_low_owid ///
	wom_emp_vdem_owid wom_emp_vdem_high_owid wom_emp_vdem_low_owid wom_civ_libs_vdem_owid wom_civ_libs_vdem_high_owid wom_civ_libs_vdem_low_owid wom_civ_soc_vdem_owid wom_civ_soc_vdem_high_owid wom_civ_soc_vdem_low_owid wom_pol_par_vdem_owid wom_pol_par_vdem_high_owid wom_pol_par_vdem_low_owid wom_parl_vdem_owid ///
	socgr_civ_libs_vdem_owid socgr_civ_libs_vdem_high_owid socgr_civ_libs_vdem_low_owid socgr_pow_vdem_owid socgr_pow_vdem_high_owid socgr_pow_vdem_low_owid ///
	terr_contr_vdem_owid terr_contr_vdem_high_owid terr_contr_vdem_low_owid rule_of_law_vdem_owid rule_of_law_vdem_high_owid rule_of_law_vdem_low_owid public_admin_vdem_owid public_admin_vdem_high_owid public_admin_vdem_low_owid int_auton_vdem_owid int_auton_vdem_high_owid int_auton_vdem_low_owid dom_auton_vdem_owid dom_auton_vdem_high_owid dom_auton_vdem_low_owid ///
	corruption_vdem_owid corruption_vdem_high_owid corruption_vdem_low_owid corr_publsec_vdem_owid corr_publsec_vdem_high_owid corr_publsec_vdem_low_owid corr_exec_vdem_owid corr_exec_vdem_high_owid corr_exec_vdem_low_owid corr_leg_vdem_owid corr_leg_vdem_high_owid corr_leg_vdem_low_owid corr_jud_vdem_owid corr_jud_vdem_high_owid corr_jud_vdem_low_owid ///
	personalism_vdem_owid personalism_vdem_high_owid personalism_vdem_low_owid civ_soc_str_vdem_owid civ_soc_str_vdem_high_owid civ_soc_str_vdem_low_owid, by(year region)
drop regime_row_owid regime_amb_row_owid electdem_age_group_row_owid libdem_age_group_row_owid wom_parl_gr_vdem_owid wom_hog_vdem_owid wom_hos_vdem_owid wom_hoe_vdem_owid

* Create entity identifier:
rename region country_name

* Rename variables:
rename regime_row_owid1 number_closedaut_row_owid
rename regime_row_owid2 number_electaut_row_owid
rename regime_row_owid3 number_electdem_row_owid
rename regime_row_owid4 number_libdem_row_owid

rename regime_amb_row_owid1 number_closedaut_amb_row_owid
rename regime_amb_row_owid2 number_closedaut_h_amb_row_owid
rename regime_amb_row_owid3 number_electaut_l_amb_row_owid
rename regime_amb_row_owid4 number_electaut_amb_row_owid
rename regime_amb_row_owid5 number_electaut_h_amb_row_owid
rename regime_amb_row_owid6 number_electdem_l_amb_row_owid
rename regime_amb_row_owid7 number_electdem_amb_row_owid
rename regime_amb_row_owid8 number_electdem_h_amb_row_owid
rename regime_amb_row_owid9 number_libdem_l_amb_row_owid
rename regime_amb_row_owid10 number_libdem_amb_row_owid

drop electdem_age_group_row_owid1 electdem_age_group_row_owid2
rename electdem_age_group_row_owid3 number_electdem_18_row_owid
rename electdem_age_group_row_owid4 number_electdem_30_row_owid
rename electdem_age_group_row_owid5 number_electdem_60_row_owid
rename electdem_age_group_row_owid6 number_electdem_90_row_owid
rename electdem_age_group_row_owid7 number_electdem_91plus_row_owid

drop libdem_age_group_row_owid1 libdem_age_group_row_owid2 libdem_age_group_row_owid3
rename libdem_age_group_row_owid4 number_libdem_18_row_owid
rename libdem_age_group_row_owid5 number_libdem_30_row_owid
rename libdem_age_group_row_owid6 number_libdem_60_row_owid
rename libdem_age_group_row_owid7 number_libdem_90_row_owid
rename libdem_age_group_row_owid8 number_libdem_91plus_row_owid

rename wom_parl_gr_vdem_owid1 number_nowomen_vdem_owid
rename wom_parl_gr_vdem_owid2 number_less10women_vdem_owid
rename wom_parl_gr_vdem_owid3 number_less20women_vdem_owid
rename wom_parl_gr_vdem_owid4 number_less30women_vdem_owid
rename wom_parl_gr_vdem_owid5 number_less40women_vdem_owid
rename wom_parl_gr_vdem_owid6 number_less50women_vdem_owid
rename wom_parl_gr_vdem_owid7 number_more50women_vdem_owid

rename wom_hog_vdem_owid1 number_hog_men_vdem_owid
rename wom_hog_vdem_owid2 number_hog_women_vdem_owid

rename wom_hos_vdem_owid1 number_hos_men_vdem_owid
rename wom_hos_vdem_owid2 number_hos_women_vdem_owid

rename wom_hoe_vdem_owid1 number_hoe_men_vdem_owid
rename wom_hoe_vdem_owid2 number_hoe_women_vdem_owid

* Temporarily save data:
save "democracy/datasets/final/vdem_row_aggregated_regions.dta", replace


** Aggregate by year and region to create regional aggregates for population-weighted sums and averages of regime variables:

* Import data:
use "democracy/datasets/refined/vdem_row_refined.dta", clear

* Add population data:
merge 1:1 country_name year using "Our World in Data/owid_population_cleaned.dta"
tab country_name if _merge == 1 & year >= 1800 // Unmerged observations in master datasets either before 1800, historical countries (Two Sicilies, East Germany) or current countries without population data (Kosovo, Palestine/Gaza, Palestine/West Bank, Somaliland).
drop _merge

* Add regional identifiers:
merge m:1 country_name using "Our World in Data/countries_regions_pairs.dta"
tab country_name if _merge == 1
replace region = "Europe" if country_name == "Brunswick" | country_name == "Hamburg" | country_name == "Nassau" | country_name == "Oldenburg" | country_name == "Papal States" | country_name == "Piedmont-Sardinia" | country_name == "Saxe-Weimar-Eisenach"
replace region = "Asia" if country_name == "Palestine/Gaza" | country_name == "Palestine/West Bank"
drop if _merge == 2
drop _merge

* Recode regime classification such that it includes a category for when population data is available, but regime data is missing:
replace regime_row_owid = 4 if regime_row_owid == . & population_owid != .
label values regime_row_owid regime_row_owid
label define regime_row_owid 4 "no regime data", add

replace regime_amb_row_owid = 10 if regime_amb_row_owid == . & population_owid != .
label values regime_amb_row_owid regime_row_owid
label define regime_amb_row_owid 10 "no regime data", add
drop if population_owid == .

replace wom_hog_vdem_owid = 3 if wom_hog_vdem_owid == . & population_owid != .
label values wom_hog_vdem_owid wom_hog_vdem_owid
label define wom_hog_vdem_owid 3 "no gender data", add

replace wom_hos_vdem_owid = 3 if wom_hos_vdem_owid == . & population_owid != .
label values wom_hos_vdem_owid wom_hos_vdem_owid
label define wom_hos_vdem_owid 3 "no gender data", add

replace wom_hoe_vdem_owid = 3 if wom_hoe_vdem_owid == . & population_owid != .
label values wom_hoe_vdem_owid wom_hoe_vdem_owid
label define wom_hoe_vdem_owid 3 "no gender data", add

* Here, I also aggregate countries with imputed values — because people matter, not countries.

* Create indicator variables for specific regime categories:
tabulate regime_row_owid, generate(regime_row_owid)
tabulate regime_amb_row_owid, generate(regime_amb_row_owid)
tabulate electdem_age_group_row_owid, generate(electdem_age_group_row_owid)
tabulate libdem_age_group_row_owid, generate(libdem_age_group_row_owid)
tabulate wom_hog_vdem_owid, generate(wom_hog_vdem_owid)
tabulate wom_hos_vdem_owid, generate(wom_hos_vdem_owid)
tabulate wom_hoe_vdem_owid, generate(wom_hoe_vdem_owid)

* Collapse dataset by year:
collapse (sum) regime_row_owid* regime_amb_row_owid* electdem_age_group_row_owid* libdem_age_group_row_owid* wom_hog_vdem_owid* wom_hos_vdem_owid* wom_hoe_vdem_owid* ///
	(mean) electdem_vdem_owid electdem_vdem_low_owid electdem_vdem_high_owid libdem_vdem_owid libdem_vdem_low_owid libdem_vdem_high_owid participdem_vdem_owid participdem_vdem_low_owid participdem_vdem_high_owid delibdem_vdem_owid delibdem_vdem_low_owid delibdem_vdem_high_owid egaldem_vdem_owid egaldem_vdem_low_owid egaldem_vdem_high_owid ///
	civ_libs_vdem_owid civ_libs_vdem_high_owid civ_libs_vdem_low_owid phys_integr_libs_vdem_owid phys_integr_libs_vdem_high_owid phys_integr_libs_vdem_low_owid pol_libs_vdem_owid pol_libs_vdem_high_owid pol_libs_vdem_low_owid priv_libs_vdem_owid priv_libs_vdem_high_owid priv_libs_vdem_low_owid ///
	wom_emp_vdem_owid wom_emp_vdem_high_owid wom_emp_vdem_low_owid wom_civ_libs_vdem_owid wom_civ_libs_vdem_high_owid wom_civ_libs_vdem_low_owid wom_civ_soc_vdem_owid wom_civ_soc_vdem_high_owid wom_civ_soc_vdem_low_owid wom_pol_par_vdem_owid wom_pol_par_vdem_high_owid wom_pol_par_vdem_low_owid wom_parl_vdem_owid ///
	socgr_civ_libs_vdem_owid socgr_civ_libs_vdem_high_owid socgr_civ_libs_vdem_low_owid socgr_pow_vdem_owid socgr_pow_vdem_high_owid socgr_pow_vdem_low_owid ///
	terr_contr_vdem_owid terr_contr_vdem_high_owid terr_contr_vdem_low_owid rule_of_law_vdem_owid rule_of_law_vdem_high_owid rule_of_law_vdem_low_owid public_admin_vdem_owid public_admin_vdem_high_owid public_admin_vdem_low_owid int_auton_vdem_owid int_auton_vdem_high_owid int_auton_vdem_low_owid dom_auton_vdem_owid dom_auton_vdem_high_owid dom_auton_vdem_low_owid ///
	corruption_vdem_owid corruption_vdem_high_owid corruption_vdem_low_owid corr_publsec_vdem_owid corr_publsec_vdem_high_owid corr_publsec_vdem_low_owid corr_exec_vdem_owid corr_exec_vdem_high_owid corr_exec_vdem_low_owid corr_leg_vdem_owid corr_leg_vdem_high_owid corr_leg_vdem_low_owid corr_jud_vdem_owid corr_jud_vdem_high_owid corr_jud_vdem_low_owid ///
	personalism_vdem_owid personalism_vdem_high_owid personalism_vdem_low_owid civ_soc_str_vdem_owid civ_soc_str_vdem_high_owid civ_soc_str_vdem_low_owid [fweight = population_owid], by(year region)
drop regime_row_owid regime_amb_row_owid regime_amb_row_owid11 electdem_age_group_row_owid libdem_age_group_row_owid wom_hog_vdem_owid wom_hos_vdem_owid wom_hoe_vdem_owid

* Create entity identifier:
rename region country_name

* Rename variables:
rename regime_row_owid1 pop_closedaut_row_owid
rename regime_row_owid2 pop_electaut_row_owid
rename regime_row_owid3 pop_electdem_row_owid
rename regime_row_owid4 pop_libdem_row_owid
rename regime_row_owid5 pop_missreg_row_owid

rename regime_amb_row_owid1 pop_closedaut_amb_row_owid
rename regime_amb_row_owid2 pop_closedaut_h_amb_row_owid
rename regime_amb_row_owid3 pop_electaut_l_amb_row_owid
rename regime_amb_row_owid4 pop_electaut_amb_row_owid
rename regime_amb_row_owid5 pop_electaut_h_amb_row_owid
rename regime_amb_row_owid6 pop_electdem_l_amb_row_owid
rename regime_amb_row_owid7 pop_electdem_amb_row_owid
rename regime_amb_row_owid8 pop_electdem_h_amb_row_owid
rename regime_amb_row_owid9 pop_libdem_l_amb_row_owid
rename regime_amb_row_owid10 pop_libdem_amb_row_owid

drop electdem_age_group_row_owid1 electdem_age_group_row_owid2
rename electdem_age_group_row_owid3 pop_electdem_18_row_owid
rename electdem_age_group_row_owid4 pop_electdem_30_row_owid
rename electdem_age_group_row_owid5 pop_electdem_60_row_owid
rename electdem_age_group_row_owid6 pop_electdem_90_row_owid
rename electdem_age_group_row_owid7 pop_electdem_91plus_row_owid

drop libdem_age_group_row_owid1 libdem_age_group_row_owid2 libdem_age_group_row_owid3
rename libdem_age_group_row_owid4 pop_libdem_18_row_owid
rename libdem_age_group_row_owid5 pop_libdem_30_row_owid
rename libdem_age_group_row_owid6 pop_libdem_60_row_owid
rename libdem_age_group_row_owid7 pop_libdem_90_row_owid
rename libdem_age_group_row_owid8 pop_libdem_91plus_row_owid

rename wom_hog_vdem_owid1 pop_hog_men_vdem_owid
rename wom_hog_vdem_owid2 pop_hog_women_vdem_owid
rename wom_hog_vdem_owid3 pop_hog_missgen_vdem_owid

rename wom_hos_vdem_owid1 pop_hos_men_vdem_owid
rename wom_hos_vdem_owid2 pop_hos_women_vdem_owid
rename wom_hos_vdem_owid3 pop_hos_missgen_vdem_owid

rename wom_hoe_vdem_owid1 pop_hoe_men_vdem_owid
rename wom_hoe_vdem_owid2 pop_hoe_women_vdem_owid
rename wom_hoe_vdem_owid3 pop_hoe_missgen_vdem_owid

rename electdem_vdem_owid popw_electdem_vdem_owid
rename electdem_vdem_low_owid popw_electdem_l_vdem_owid
rename electdem_vdem_high_owid popw_electdem_h_vdem_owid

rename libdem_vdem_owid popw_libdem_vdem_owid
rename libdem_vdem_low_owid popw_libdem_l_vdem_owid
rename libdem_vdem_high_owid popw_libdem_h_vdem_owid

rename participdem_vdem_owid popw_participdem_vdem_owid
rename participdem_vdem_low_owid popw_participdem_l_vdem_owid
rename participdem_vdem_high_owid popw_participdem_h_vdem_owid

rename delibdem_vdem_owid popw_delibdem_vdem_owid
rename delibdem_vdem_low_owid popw_delibdem_l_vdem_owid
rename delibdem_vdem_high_owid popw_delibdem_h_vdem_owid

rename egaldem_vdem_owid popw_egaldem_vdem_owid
rename egaldem_vdem_low_owid popw_egaldem_l_vdem_owid
rename egaldem_vdem_high_owid popw_egaldem_h_vdem_owid

rename civ_libs_vdem_owid popw_civ_libs_vdem_owid
rename civ_libs_vdem_high_owid popw_civ_libs_vdem_high_owid
rename civ_libs_vdem_low_owid popw_civ_libs_vdem_low_owid

rename phys_integr_libs_vdem_owid popw_physinteg_libs_vdem_owid
rename phys_integr_libs_vdem_high_owid popw_physinteg_libs_vdem_h_owid
rename phys_integr_libs_vdem_low_owid popw_physinteg_libs_vdem_l_owid

rename pol_libs_vdem_owid popw_pol_libs_vdem_owid
rename pol_libs_vdem_high_owid popw_pol_libs_vdem_high_owid
rename pol_libs_vdem_low_owid popw_pol_libs_vdem_low_owid

rename priv_libs_vdem_owid popw_priv_libs_vdem_owid
rename priv_libs_vdem_high_owid popw_priv_libs_vdem_high_owid
rename priv_libs_vdem_low_owid popw_priv_libs_vdem_low_owid

rename wom_emp_vdem_owid popw_wom_emp_vdem_owid
rename wom_emp_vdem_high_owid popw_wom_emp_vdem_high_owid
rename wom_emp_vdem_low_owid popw_wom_emp_vdem_low_owid

rename wom_civ_libs_vdem_owid popw_wom_civ_libs_vdem_owid
rename wom_civ_libs_vdem_high_owid popw_wom_civ_libs_vdem_high_owid
rename wom_civ_libs_vdem_low_owid popw_wom_civ_libs_vdem_low_owid

rename wom_civ_soc_vdem_owid popw_wom_civ_soc_vdem_owid
rename wom_civ_soc_vdem_high_owid popw_wom_civ_soc_vdem_high_owid
rename wom_civ_soc_vdem_low_owid popw_wom_civ_soc_vdem_low_owid

rename wom_pol_par_vdem_owid popw_wom_pol_par_vdem_owid
rename wom_pol_par_vdem_high_owid popw_wom_pol_par_vdem_high_owid
rename wom_pol_par_vdem_low_owid popw_wom_pol_par_vdem_low_owid

rename wom_parl_vdem_owid popw_wom_parl_vdem_owid

rename socgr_civ_libs_vdem_owid popw_socgr_civ_libs_vdem_owid
rename socgr_civ_libs_vdem_high_owid popw_socgr_civ_libs_vdem_h_owid
rename socgr_civ_libs_vdem_low_owid popw_socgr_civ_libs_vdem_l_owid

rename socgr_pow_vdem_owid popw_socgr_pow_vdem_owid
rename socgr_pow_vdem_high_owid popw_socgr_pow_vdem_high_owid
rename socgr_pow_vdem_low_owid popw_socgr_pow_vdem_low_owid

rename terr_contr_vdem_owid popw_terr_contr_vdem_owid
rename terr_contr_vdem_high_owid popw_terr_contr_vdem_high_owid
rename terr_contr_vdem_low_owid popw_terr_contr_vdem_low_owid

rename rule_of_law_vdem_owid popw_rule_of_law_vdem_owid
rename rule_of_law_vdem_high_owid popw_rule_of_law_vdem_high_owid
rename rule_of_law_vdem_low_owid popw_rule_of_law_vdem_low_owid

rename public_admin_vdem_owid popw_public_admin_vdem_owid
rename public_admin_vdem_high_owid popw_public_admin_vdem_high_owid
rename public_admin_vdem_low_owid popw_public_admin_vdem_low_owid

rename int_auton_vdem_owid popw_int_auton_vdem_owid
rename int_auton_vdem_high_owid popw_int_auton_vdem_high_owid
rename int_auton_vdem_low_owid popw_int_auton_vdem_low_owid

rename dom_auton_vdem_owid popw_dom_auton_vdem_owid
rename dom_auton_vdem_high_owid popw_dom_auton_vdem_high_owid
rename dom_auton_vdem_low_owid popw_dom_auton_vdem_low_owid

rename corruption_vdem_owid popw_corruption_vdem_owid
rename corruption_vdem_high_owid popw_corruption_vdem_high_owid
rename corruption_vdem_low_owid popw_corruption_vdem_low_owid

rename corr_publsec_vdem_owid popw_corr_publsec_vdem_owid
rename corr_publsec_vdem_high_owid popw_corr_publsec_vdem_high_owid
rename corr_publsec_vdem_low_owid popw_corr_publsec_vdem_low_owid

rename corr_exec_vdem_owid popw_corr_exec_vdem_owid
rename corr_exec_vdem_high_owid popw_corr_exec_vdem_high_owid
rename corr_exec_vdem_low_owid popw_corr_exec_vdem_low_owid

rename corr_leg_vdem_owid popw_corr_leg_vdem_owid
rename corr_leg_vdem_high_owid popw_corr_leg_vdem_high_owid
rename corr_leg_vdem_low_owid popw_corr_leg_vdem_low_owid

rename corr_jud_vdem_owid popw_corr_jud_vdem_owid
rename corr_jud_vdem_high_owid popw_corr_jud_vdem_high_owid
rename corr_jud_vdem_low_owid popw_corr_jud_vdem_low_owid

rename personalism_vdem_owid popw_personalism_vdem_owid
rename personalism_vdem_high_owid popw_personalism_vdem_high_owid
rename personalism_vdem_low_owid popw_personalism_vdem_low_owid

rename civ_soc_str_vdem_owid popw_civ_soc_str_vdem_owid
rename civ_soc_str_vdem_high_owid popw_civ_soc_str_vdem_high_owid
rename civ_soc_str_vdem_low_owid popw_civ_soc_str_vdem_low_owid

* Temporarily save data:
save "democracy/datasets/final/vdem_row_aggregated_popweighted_regions.dta", replace


** Merge different datasets:
use "democracy/datasets/refined/vdem_row_refined.dta"
merge 1:1 country_name year using "democracy/datasets/final/vdem_row_aggregated.dta"
drop _merge
merge 1:1 country_name year using "democracy/datasets/final/vdem_row_aggregated_popweighted.dta"
drop _merge
merge 1:1 country_name year using "democracy/datasets/final/vdem_row_aggregated_regions.dta"
drop _merge
merge 1:1 country_name year using "democracy/datasets/final/vdem_row_aggregated_popweighted_regions.dta", update
drop _merge
erase "democracy/datasets/final/vdem_row_aggregated.dta"
erase "democracy/datasets/final/vdem_row_aggregated_popweighted.dta"
erase "democracy/datasets/final/vdem_row_aggregated_regions.dta"
erase "democracy/datasets/final/vdem_row_aggregated_popweighted_regions.dta"


** Add regional identifiers to final dataset:
merge m:1 country_name using "Our World in Data/countries_regions_pairs.dta"
tab country_name if _merge == 1
replace region = "Europe" if country_name == "Brunswick" | country_name == "Hamburg" | country_name == "Nassau" | country_name == "Oldenburg" | country_name == "Papal States" | country_name == "Piedmont-Sardinia" | country_name == "Saxe-Weimar-Eisenach"
replace region = "Asia" if country_name == "Palestine/Gaza" | country_name == "Palestine/West Bank"
replace region = "World" if country_name == "World"
drop if _merge == 2
drop _merge


** Refine variables:
replace number_nowomen_vdem_owid = . if year < 1900 // underlying variable only available since 1900.
replace number_less10women_vdem_owid = . if year < 1900
replace number_less20women_vdem_owid = . if year < 1900
replace number_less30women_vdem_owid = . if year < 1900
replace number_less40women_vdem_owid = . if year < 1900
replace number_less50women_vdem_owid = . if year < 1900
replace number_more50women_vdem_owid = . if year < 1900


** Label variables:
label variable number_closedaut_row_owid "Number of closed autocracies (RoW, OWID)"
label variable number_electaut_row_owid "Number of electoral autocracies (RoW, OWID)"
label variable number_electdem_row_owid "Number of electoral democracies (RoW, OWID)"
label variable number_libdem_row_owid "Number of liberal democracies (RoW, OWID)"

label variable pop_closedaut_row_owid "People living in closed autocracies (RoW, OWID)"
label variable pop_electaut_row_owid "People living in electoral autocracies (RoW, OWID)"
label variable pop_electdem_row_owid "People living in electoral democracies (RoW, OWID)"
label variable pop_libdem_row_owid "People living in liberal democracies (RoW, OWID)"
label variable pop_missreg_row_owid "People living in countries without regime data (RoW, OWID)"

label variable number_closedaut_amb_row_owid "Number of closed autocracies (ambig. RoW, OWID)"
label variable number_closedaut_h_amb_row_owid "Number of closed, maybe electoral, autocracies (ambig. RoW, OWID)"
label variable number_electaut_l_amb_row_owid "Number of electoral, maybe closed, autocracies (ambig. RoW, OWID)"
label variable number_electaut_amb_row_owid "Number of electoral autocracies (ambig. RoW, OWID)"
label variable number_electaut_h_amb_row_owid "Number of electoral autocracies that may be electoral democracies (ambig. RoW, OWID)"
label variable number_electdem_l_amb_row_owid "Number of electoral democracies that may be electoral autocracies (ambig. RoW, OWID)"
label variable number_electdem_amb_row_owid "Number of electoral democracies (ambig. RoW, OWID)"
label variable number_electdem_h_amb_row_owid "Number of electoral, maybe liberal, democracies (ambig. RoW, OWID)"
label variable number_libdem_l_amb_row_owid "Number of liberal, maybe electoral, democracies (ambig. RoW, OWID)"
label variable number_libdem_amb_row_owid "Number of liberal democracies (ambig. RoW, OWID)"

label variable pop_closedaut_amb_row_owid "People living in closed autocracies (ambig. RoW, OWID)"
label variable pop_closedaut_h_amb_row_owid "People living in closed, maybe electoral, autocracies (ambig. RoW, OWID)"
label variable pop_electaut_l_amb_row_owid "People living in electoral, maybe closed, autocracies (ambig. RoW, OWID)"
label variable pop_electaut_amb_row_owid "People living in electoral autocracies (ambig. RoW, OWID)"
label variable pop_electaut_h_amb_row_owid "People living in electoral autocracies that may be electoral democracies (ambig. RoW, OWID)"
label variable pop_electdem_l_amb_row_owid "People living in electoral democracies that may be electoral autocracies (ambig. RoW, OWID)"
label variable pop_electdem_amb_row_owid "People living in electoral democracies (ambig. RoW, OWID)"
label variable pop_electdem_h_amb_row_owid "People living in electoral, maybe liberal, democracies (ambig. RoW, OWID)"
label variable pop_libdem_l_amb_row_owid "People living in liberal, maybe electoral, democracies (ambig. RoW, OWID)"
label variable pop_libdem_amb_row_owid "People living in liberal democracies (ambig. RoW, OWID)"

label variable number_electdem_18_row_owid "Number of electoral democracies aged 1-18 years (RoW, OWID)"
label variable number_electdem_30_row_owid "Number of electoral democracies aged 19-30 years (RoW, OWID)"
label variable number_electdem_60_row_owid "Number of electoral democracies aged 31-60 years (RoW, OWID)"
label variable number_electdem_90_row_owid "Number of electoral democracies aged 61-90 years (RoW, OWID)"
label variable number_electdem_91plus_row_owid "Number of electoral democracies aged 91 years or older (RoW, OWID)"

label variable number_libdem_18_row_owid "Number of liberal democracies aged 1-18 years (RoW, OWID)"
label variable number_libdem_30_row_owid "Number of liberal democracies aged 19-30 years (RoW, OWID)"
label variable number_libdem_60_row_owid "Number of liberal democracies aged 31-60 years (RoW, OWID)"
label variable number_libdem_90_row_owid "Number of liberal democracies aged 61-90 years (RoW, OWID)"
label variable number_libdem_91plus_row_owid "Number of liberal democracies aged 91 years or older (RoW, OWID)"

label variable pop_electdem_18_row_owid "People living in electoral democracies aged 1-18 years (RoW, OWID)"
label variable pop_electdem_30_row_owid "People living in electoral democracies aged 19-30 years (RoW, OWID)"
label variable pop_electdem_60_row_owid "People living in electoral democracies aged 31-60 years (RoW, OWID)"
label variable pop_electdem_90_row_owid "People living in electoral democracies aged 61-90 years (RoW, OWID)"
label variable pop_electdem_91plus_row_owid "People living in electoral democracies aged 91 years or older (RoW, OWID)"

label variable pop_libdem_18_row_owid "People living in liberal democracies aged 1-18 years (RoW, OWID)"
label variable pop_libdem_30_row_owid "People living in liberal democracies aged 19-30 years (RoW, OWID)"
label variable pop_libdem_60_row_owid "People living in liberal democracies aged 31-60 years (RoW, OWID)"
label variable pop_libdem_90_row_owid "People living in liberal democracies aged 61-90 years (RoW, OWID)"
label variable pop_libdem_91plus_row_owid "People living in liberal democracies aged 91 years or older (RoW, OWID)"

label variable popw_electdem_vdem_owid "Electoral democracy (V-Dem, population-weighted)"
label variable popw_electdem_l_vdem_owid "Electoral democracy (lower bound, pop-weighted, V-Dem)"
label variable popw_electdem_h_vdem_owid "Electoral democracy (upper bound, pop-weighted, V-Dem)"

label variable popw_libdem_vdem_owid "Liberal democracy (V-Dem, population-weighted)"
label variable popw_libdem_l_vdem_owid "Liberal democracy (lower bound, pop-weighted, V-Dem)"
label variable popw_libdem_h_vdem_owid "Liberal democracy (upper bound, pop-weighted, V-Dem)"

label variable popw_participdem_vdem_owid "Participatory democracy (V-Dem, population-weighted)"
label variable popw_participdem_l_vdem_owid "Participatory democracy (lower bound, pop-weighted, V-Dem)"
label variable popw_participdem_h_vdem_owid "Participatory democracy (upper bound, pop-weighted, V-Dem)"

label variable popw_delibdem_vdem_owid "Deliberative democracy (V-Dem, population-weighted)"
label variable popw_delibdem_l_vdem_owid "Deliberative democracy (lower bound, pop-weighted, V-Dem)"
label variable popw_delibdem_h_vdem_owid "Deliberative democracy (upper bound, pop-weighted, V-Dem)"

label variable popw_egaldem_vdem_owid "Egalitarian democracy (V-Dem, population-weighted)"
label variable popw_egaldem_l_vdem_owid "Egalitarian democracy (lower bound, pop-weighted, V-Dem)"
label variable popw_egaldem_h_vdem_owid "Egalitarian democracy (upper bound, pop-weighted, V-Dem)"

label variable popw_civ_libs_vdem_owid "Civil liberties (V-Dem, population-weighted)"
label variable popw_civ_libs_vdem_low_owid "Civil liberties (lower bound, pop-weighted, V-Dem)"
label variable popw_civ_libs_vdem_high_owid "Civil liberties (upper bound, pop-weighted, V-Dem)"

label variable popw_physinteg_libs_vdem_owid "Physical integrity liberties (V-Dem, population-weighted)"
label variable popw_physinteg_libs_vdem_l_owid "Physical integrity liberties (lower bound, pop-weighted, V-Dem)"
label variable popw_physinteg_libs_vdem_h_owid "Physical integrity liberties (upper bound, pop-weighted, V-Dem)"

label variable popw_pol_libs_vdem_owid "Political civil liberties (V-Dem, population-weighted)"
label variable popw_pol_libs_vdem_low_owid "Political civil liberties (lower bound, pop-weighted, V-Dem)"
label variable popw_pol_libs_vdem_high_owid "Political civil liberties (upper bound, pop-weighted, V-Dem)"

label variable popw_priv_libs_vdem_owid "Private civil liberties (V-Dem, population-weighted)"
label variable popw_priv_libs_vdem_low_owid "Private civil liberties (lower bound, pop-weighted, V-Dem)"
label variable popw_priv_libs_vdem_high_owid "Private civil liberties (upper bound, pop-weighted, V-Dem)"

label variable number_nowomen_vdem_owid "Number of countries with no women in parliament (V-Dem, OWID)"
label variable number_less10women_vdem_owid "Number of countries with 0-10% women in parliament (V-Dem, OWID)"
label variable number_less20women_vdem_owid "Number of countries with 10-20% women in parliament (V-Dem, OWID)"
label variable number_less30women_vdem_owid "Number of countries with 20-30% women in parliament (V-Dem, OWID)"
label variable number_less40women_vdem_owid "Number of countries with 30-40% women in parliament (V-Dem, OWID)"
label variable number_less50women_vdem_owid "Number of countries with 40-50% women in parliament (V-Dem, OWID)"
label variable number_more50women_vdem_owid "Number of countries with more than 50% women in parliament (V-Dem, OWID)"

label variable number_hog_men_vdem_owid "Number of countries in which head of government is a woman (V-Dem)"
label variable number_hog_women_vdem_owid "Number of countries in which head of government is a man (V-Dem)"

label variable pop_hog_men_vdem_owid "People living in countries in which head of government is a woman (V-Dem)"
label variable pop_hog_women_vdem_owid "People living in countries in which head of government is a man (V-Dem)"
label variable pop_hog_missgen_vdem_owid "People living in countries without data on head of government's gender (V-Dem)"

label variable number_hos_men_vdem_owid "Number of countries in which head of state is a woman (V-Dem)"
label variable number_hos_women_vdem_owid "Number of countries in which head of state is a man (V-Dem)"

label variable pop_hos_men_vdem_owid "People living in countries in which head of state is a woman (V-Dem)"
label variable pop_hos_women_vdem_owid "People living in countries in which head of state is a man (V-Dem)"
label variable pop_hos_missgen_vdem_owid "People living in countries without data on head of state's gender (V-Dem)"

label variable number_hoe_men_vdem_owid "Number of countries in which chief executive is a woman (V-Dem)"
label variable number_hoe_women_vdem_owid "Number of countries in which chief executive is a man (V-Dem)"

label variable pop_hoe_men_vdem_owid "People living in countries in which chief executive is a woman (V-Dem)"
label variable pop_hoe_women_vdem_owid "People living in countries in which chief executive is a man (V-Dem)"
label variable pop_hoe_missgen_vdem_owid "People living in countries without data on chief executive's gender (V-Dem)"

label variable popw_wom_emp_vdem_owid "Women's political empowerment (V-Dem, population-weighted)"
label variable popw_wom_emp_vdem_high_owid "Women's political empowerment (upper bound, pop-weighted, V-Dem)"
label variable popw_wom_emp_vdem_low_owid "Women's political empowerment (lower bound, pop-weighted, V-Dem)"

label variable popw_wom_civ_libs_vdem_owid "Women's civil rights (V-Dem, population-weighted)"
label variable popw_wom_civ_libs_vdem_high_owid "Women's civil rights (upper bound, pop-weighted, V-Dem)"
label variable popw_wom_civ_libs_vdem_low_owid "Women's civil rights (lower bound, pop-weighted, V-Dem)"

label variable popw_wom_civ_soc_vdem_owid "Women's civil society partipation (V-Dem, population-weighted)"
label variable popw_wom_civ_soc_vdem_high_owid "Women's civil society partipation (upper bound, pop-weighted, V-Dem)"
label variable popw_wom_civ_soc_vdem_low_owid "Women's civil society partipation (lower bound, pop-weighted, V-Dem)"

label variable popw_wom_pol_par_vdem_owid "Women's political partipation (V-Dem, population-weighted)"
label variable popw_wom_pol_par_vdem_high_owid "Women's political partipation (upper bound, pop-weighted, V-Dem)"
label variable popw_wom_pol_par_vdem_low_owid "Women's political partipation (lower bound, pop-weighted, V-Dem)"

label variable popw_wom_parl_vdem_owid "Women in parliament (V-Dem, population-weighted)"

label variable popw_socgr_civ_libs_vdem_owid "Equality of civil liberties across social groups (V-Dem, population-weighted)"
label variable popw_socgr_civ_libs_vdem_h_owid "Equality of civil liberties across social groups (upper bound, pop-weighted, V-Dem)"
label variable popw_socgr_civ_libs_vdem_l_owid "Equality of civil liberties across social groups (lower bound, pop-weighted, V-Dem)"

label variable popw_socgr_pow_vdem_owid "Equality of political power across social groups (V-Dem, population-weighted)"
label variable popw_socgr_pow_vdem_high_owid "Equality of political power across social groups (upper bound, pop-weighted V-Dem)"
label variable popw_socgr_pow_vdem_low_owid "Equality of political power across social groups (upper bound, pop-weighted V-Dem)"

label variable popw_terr_contr_vdem_owid "Territory under state control (V-Dem, population-weighted)"
label variable popw_terr_contr_vdem_high_owid "Territory under state control (upper bound, pop-weighted, V-Dem)"
label variable popw_terr_contr_vdem_low_owid "Territory under state control (lower bound, pop-weighted, V-Dem)"

label variable popw_rule_of_law_vdem_owid "Rule of Law (V-Dem, population-weighted)"
label variable popw_rule_of_law_vdem_high_owid "Rule of Law (upper bound, pop-weighted, V-Dem)"
label variable popw_rule_of_law_vdem_low_owid "Rule of Law (lower bound, pop-weighted, V-Dem)"

label variable popw_public_admin_vdem_owid "Rigorous and impartial public administration (V-Dem, population-weighted)"
label variable popw_public_admin_vdem_high_owid "Rigorous and impartial public administration (upper bound, pop-weighted, V-Dem)"
label variable popw_public_admin_vdem_low_owid "Rigorous and impartial public administration (lower bound, pop-weighted, V-Dem)"

label variable popw_int_auton_vdem_owid "Foreign policymaking free from foreign influence (V-Dem, population-weighted)"
label variable popw_int_auton_vdem_high_owid "Foreign policymaking free from foreign influence (upper bound, pop-weighted, V-Dem)"
label variable popw_int_auton_vdem_low_owid "Foreign policymaking free from foreign influence (lower bound, pop-weighted, V-Dem)"

label variable popw_dom_auton_vdem_owid "Domestic policymaking free from foreign influence (V-Dem, population-weighted)"
label variable popw_dom_auton_vdem_high_owid "Domestic policymaking free from foreign influence (upper bound, pop-weighted, V-Dem)"
label variable popw_dom_auton_vdem_low_owid "Domestic policymaking free from foreign influence (upper bound, pop-weighted, V-Dem)"

label variable popw_corruption_vdem_owid "Political corruption (V-Dem, population-weighted)"
label variable popw_corruption_vdem_high_owid "Political corruption (upper bound, pop-weighted, V-Dem)"
label variable popw_corruption_vdem_low_owid "Political corruption (lower bound, pop-weighted, V-Dem)"

label variable popw_corr_publsec_vdem_owid "Public sector corruption (V-Dem, population-weighted)"
label variable popw_corr_publsec_vdem_high_owid "Public sector corruption (upper bound, pop-weighted, V-Dem)"
label variable popw_corr_publsec_vdem_low_owid "Public sector corruption (lower bound, pop-weighted, V-Dem)"

label variable popw_corr_exec_vdem_owid "Executive corruption (V-Dem, population-weighted)"
label variable popw_corr_exec_vdem_high_owid "Executive corruption (upper bound, pop-weighted, V-Dem)"
label variable popw_corr_exec_vdem_low_owid "Executive corruption (lower bound, pop-weighted, V-Dem)"

label variable popw_corr_leg_vdem_owid "Legislative corruption (V-Dem, population-weighted)"
label variable popw_corr_leg_vdem_high_owid "Legislative corruption (upper bound, pop-weighted, V-Dem)"
label variable popw_corr_leg_vdem_low_owid "Legislative corruption (lower bound, pop-weighted, V-Dem)"

label variable popw_corr_jud_vdem_owid "Judicial corruption (V-Dem, population-weighted)"
label variable popw_corr_jud_vdem_high_owid "Judicial corruption (upper bound, pop-weighted, V-Dem)"
label variable popw_corr_jud_vdem_low_owid "Judicial corruption (upper bound, pop-weighted, V-Dem)"

label variable popw_personalism_vdem_owid "Personalism (V-Dem, population-weighted)"
label variable popw_personalism_vdem_high_owid "Personalism (upper bound, pop-weighted, V-Dem)"
label variable popw_personalism_vdem_low_owid "Personalism (lower bound, pop-weighted, V-Dem)"

label variable popw_civ_soc_str_vdem_owid "Civil society strength (V-Dem, population-weighted)"
label variable popw_civ_soc_str_vdem_high_owid "Civil society strength (upper bound, pop-weighted, V-Dem)"
label variable popw_civ_soc_str_vdem_low_owid "Civil society strength (lower bound, pop-weighted, V-Dem)"
	
label variable region "Region"


** Order observations:
sort country_name year


** Export data:
save "democracy/datasets/final/vdem_row_final.dta", replace
export delimited "democracy/datasets/final/vdem_row_final.csv", replace nolabel

describe, replace
keep name varlab
rename name varname
rename varlab varlabel
export delimited "democracy/datasets/final/vdem_row_final_meta.csv", replace


exit
